version: '3'
services:
  frontend:
    build:
       context: ./front
    # image: front:latest
    ports:
      - "80:80"

  mariadb:
    image: mariadb:latest
    #build:
       #context: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/sql-files/db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql # dossier de stockage des données de la DB
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./back  
    # image: back:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: charmettes
      DB_USER: charmettes
      DB_PASSWORD: charmettes
    links:
      - mariadb
    depends_on:
      - mariadb
