version: '3'
services:
  frontend:
    restart: always
    build:
       context: ./front
    # image: front:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro   ## ro pour read only
  
  # serveur cerbot pour generer les certificat et les  partager sur dossier  coomun en rw
  # pour lancer la commende -- docker compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d test.magavel.ovh
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      
      


# based e données
  mariadb:
    image: mariadb:latest
    #build:
       #context: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/sql-files/db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql # dossier de stockage des données de la DB
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./back  
    # image: back:latest
    ports:
      - "3000:3000"
    links:
      - mariadb
    depends_on:
      - mariadb
